// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzPmO8VCJAlXXzJJ2U1XWKEC_t3z0hMXs',
    appId: '1:747234878368:web:a195cd82c46579f2b43ac5',
    messagingSenderId: '747234878368',
    projectId: 'todo-e748c',
    authDomain: 'todo-e748c.firebaseapp.com',
    storageBucket: 'todo-e748c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6q7-yt0_nYO2W0J7FxNJQyW6nSb-_RXE',
    appId: '1:747234878368:android:ee5d11cce8099fa1b43ac5',
    messagingSenderId: '747234878368',
    projectId: 'todo-e748c',
    storageBucket: 'todo-e748c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTtv3kPb5m8EJ4HSUIGnfgZiuPftSO4so',
    appId: '1:747234878368:ios:17e5a570ed3d2557b43ac5',
    messagingSenderId: '747234878368',
    projectId: 'todo-e748c',
    storageBucket: 'todo-e748c.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTtv3kPb5m8EJ4HSUIGnfgZiuPftSO4so',
    appId: '1:747234878368:ios:17e5a570ed3d2557b43ac5',
    messagingSenderId: '747234878368',
    projectId: 'todo-e748c',
    storageBucket: 'todo-e748c.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzPmO8VCJAlXXzJJ2U1XWKEC_t3z0hMXs',
    appId: '1:747234878368:web:b9b8a24995cf3a69b43ac5',
    messagingSenderId: '747234878368',
    projectId: 'todo-e748c',
    authDomain: 'todo-e748c.firebaseapp.com',
    storageBucket: 'todo-e748c.appspot.com',
  );
}
